using UnityEngine;
using UnityEngine.UI;
using TMPro;
using Unity.Services.Core;
using Unity.Services.Authentication;
using Unity.Services.Multiplayer;
using Unity.Netcode;
using System.Threading.Tasks;

/// <summary>
/// Manages lobby UI stuff and the creation/joining multiplayer sessions with unity multiplayer services
/// For named sessions for connecting players rather than hardcoded IP addresses
/// Handles hosting and joining sessions, updating lobby status messages, and switching from lobby UI to game UI when a session starts
/// </summary>
public class LobbyManager : MonoBehaviour
{
    [Header("Lobby UI References")]
    [SerializeField] private GameObject lobbyPanel; //panel shown before game starts with host/join options
    [SerializeField] private GameObject gamePanel; //panel containing the board and game UI, hidden until game starts
    [SerializeField] private TMP_InputField sessionNameInput; //input field for typing session name to create or join, also used to enter join code when joining
    [SerializeField] private TextMeshProUGUI statusText; //text to show lobby status messages to the player
    [SerializeField] private Button hostButton; //button to create/host a new session
    [SerializeField] private Button joinButton; //button to join an existing session by code

    //reference to the current multiplayer session
    private ISession currentSession;

    //tracks whether unity services have been initialized
    private bool servicesInitialized = false;

    private async void Start()
    {
        //initialize unity gaming services on startup
        await InitializeServices();
    }

    //initializes unity gaming services and sign ins
    //anonymous sign ins
    //done before any lobby and relay calls
    private async Task InitializeServices()
    {
        try
        {
            //initialize unity services
            await UnityServices.InitializeAsync();

            //sign in anonymously if not already signed in
            if (!AuthenticationService.Instance.IsSignedIn)
            {
                await AuthenticationService.Instance.SignInAnonymouslyAsync();
            }

            servicesInitialized = true;
            SetStatus("Host: enter a session name. Join: enter the join code from host.");
        }
        catch (System.Exception e)
        {
            SetStatus("Failed to initialize services: " + e.Message);
            Debug.LogError("Failed to initialize Unity Services: " + e);
        }
    }

    //called when host button clicked
    //creates new named session and displays the join code for player 2 to enter
    //uses unity multiplayer services session management for this so wont have to hard code ip
    public async void OnHostButtonClicked()
    {
        //make sure services are ready and a session name has been entered
        if (!servicesInitialized)
        {
            SetStatus("Services not ready yet.");
            return;
        }

        string sessionName = sessionNameInput.text.Trim();
        if (string.IsNullOrEmpty(sessionName))
        {
            SetStatus("Enter a session name to host.");
            return;
        }

        //disable buttons while connecting to prevent double clicks
        SetButtonsInteractable(false);
        SetStatus("Creating session: " + sessionName);

        try
        {
            //create session options w/ max 2 players
            var options = new SessionOptions()
            {
                Name = sessionName,
                MaxPlayers = 2
            }.WithRelayNetwork(); //use relay so players dont need to port forward or share IPs

            //create the session via Unity Multiplayer Services
            currentSession = await MultiplayerService.Instance.CreateSessionAsync(options);

            //display the join code (session.Code) so host can share it with player 2
            //Code is the correct ISession property for the relay join code
            SetStatus("Session created! Share this join code with player 2: " + currentSession.Code);

            //switch from lobby UI to game UI
            ShowGamePanel();
        }
        catch (System.Exception e)
        {
            SetStatus("Failed to create session: " + e.Message);
            Debug.LogError("Session creation error: " + e);
            SetButtonsInteractable(true);
        }
    }

    //called when join button clicked
    //joins an existing session using the join code generated by the host
    public async void OnJoinButtonClicked()
    {
        //make sure services are ready and a join code has been entered
        if (!servicesInitialized)
        {
            SetStatus("Services not ready yet.");
            return;
        }

        string joinCode = sessionNameInput.text.Trim();
        if (string.IsNullOrEmpty(joinCode))
        {
            SetStatus("Enter the join code from the host.");
            return;
        }

        //disable buttons while connecting
        SetButtonsInteractable(false);
        SetStatus("Joining session with code: " + joinCode);

        try
        {
            //join session by code using Unity Multiplayer Services
            //JoinSessionByCodeAsync takes the relay join code displayed to the host after session creation
            currentSession = await MultiplayerService.Instance.JoinSessionByCodeAsync(joinCode);

            SetStatus("Joined session, starting game.");

            //switch from lobby UI to game UI
            ShowGamePanel();
        }
        catch (System.Exception e)
        {
            SetStatus("Failed to join session: " + e.Message);
            Debug.LogError("Session join error: " + e);
            SetButtonsInteractable(true);
        }
    }

    //helper to switch from lobby UI to game UI when session starts
    private void ShowGamePanel()
    {
        //hide lobby panel buttons and input but keep status text visible so host can see and share the join code
        if (sessionNameInput != null) sessionNameInput.gameObject.SetActive(false);
        if (hostButton != null) hostButton.gameObject.SetActive(false);
        if (joinButton != null) joinButton.gameObject.SetActive(false);

        //show game panel
        if (gamePanel != null) gamePanel.SetActive(true);

        //allows cell clicks bc game started and players connected
        foreach (var cell in FindObjectsByType<CellInteraction>(FindObjectsSortMode.None))
        {
            cell.SetGameStarted(true);
        }

        //scene networkobjects like the game manager are auto-spawned by netcode when the host starts, no manual spawn needed
    }

    //when the lobby manager is destroyed (like when quitting back to main menu), leave the session if we're in one
    private async void OnDestroy()
    {
        if (currentSession != null)
        {
            await currentSession.LeaveAsync();
        }
    }

    //helper to update status text
    private void SetStatus(string message)
    {
        if (statusText != null)
            statusText.text = message;
    }

    //helper to enable or disable host and join buttons
    private void SetButtonsInteractable(bool interactable)
    {
        if (hostButton != null) hostButton.interactable = interactable;
        if (joinButton != null) joinButton.interactable = interactable;
    }
}
